# Makefile for Generator Program

COMPILER_TYPE = -std = gnu99

CC = gcc

PROG = main
SRCS = noncanonical.c

CFLAGS = 

$(PROG) : $(SRCS)
	$(CC) $(CFLAGS) $(SRCS) -o $(PROG)

clean:
	rm -f program
	rm -f .depend
	rm -f *.d
rm -f *.o